NETWORK_MANAGER_WIREGUARD_VERSION = 61646ade26750c52626a44b025cb1b165681c662
NETWORK_MANAGER_WIREGUARD_SITE = https://github.com/max-moser/network-manager-wireguard.git
NETWORK_MANAGER_WIREGUARD_SITE_METHOD = git
NETWORK_MANAGER_WIREGUARD_AUTORECONF = YES
NETWORK_MANAGER_WIREGUARD_CONF_OPTS = --without-gnome
NETWORK_MANAGER_WIREGUARD_DEPENDENCIES = host-intltool

define NETWORK_MANAGER_WIREGUARD_RUN_INTLTOOLIZE
	cd $(@D) && $(HOST_DIR)/usr/bin/intltoolize --force --automake
endef
NETWORK_MANAGER_WIREGUARD_PRE_CONFIGURE_HOOKS += NETWORK_MANAGER_WIREGUARD_RUN_INTLTOOLIZE

$(eval $(autotools-package))
